image: python:3.6

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install coverage flake8

django-test:
  stage: test
  script:
    - coverage run test.py
    - coverage report
    - flake8
